namespace: phpipam
replicaCount: 1
nodeSelector: {}
affinity: {}
tolerations: {}

additionalConfigMaps: []
  # - name: ldap-config
  #   data:
  #     ldap.conf: |
  #       ...
  #       TLS_CACERT /etc/ipa/ca.crt
  #       ...

additionalVolumes: []
  # - name: ldap-config
  #   configMap:
  #     name: ldap-config

  # An example of a secret that can be mounted on /etc/ipa/ca.crt containing the CA certificate
  # The secret should be created in the same namespace as the phpipam deployment
  # - name: ldap-ca-cert
  #   secret:
  #     secretName: ldap-ca-cert

phpipamWeb:
  name: phpipam-web
  image:
    repository: phpipam/phpipam-www
    tag: 1.5x
    pullPolicy: IfNotPresent

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    extraLabels: {}
    pathType: Prefix
    path: /
    host: phpipam.example.local
    pathType: Prefix
    tls: []
      # - secretName: phpipam-ssl-certificate
      #   hosts:
      #     - phpipam.example.local

  resources: {}
    # requests:
    #   memory: 128Mi
    #   cpu: 0.1
    # limits:
    #   memory: 256Mi
    #   cpu: 0.5

  env:
    - name: TZ
      value: America/Los_Angeles
    - name: IPAM_DATABASE_HOST
      value: phpipam-db
    - name: IPAM_DATABASE_WEBHOST
      value: "%"
    - name: IPAM_DATABASE_PASS
      valueFrom:
        secretKeyRef:
          key: password
          name: mysql-password
  service:
    port: 80
    type: ClusterIP

phpipamCron:
  name: phpipam-cron
  image:
    repository: phpipam/phpipam-cron
    tag: 1.6x
    pullPolicy: IfNotPresent
  env:
    - name: IPAM_DATABASE_HOST
      value: phpipam-db
    - name: IPAM_DATABASE_PASS
      valueFrom:
        secretKeyRef:
          key: password
          name: mysql-password
    - name: SCAN_INTERVAL
      value: 1h
    - name: TZ
      value: America/Los_Angeles

  resources: {}
    # requests:
    #   memory: 128Mi
    #   cpu: 0.1
    # limits:
    #   memory: 256Mi
    #   cpu: 0.5

phpipamMariadb:
  name: phpipam-db
  image:
    repository: mariadb
    tag: 10.7.3
    pullPolicy: IfNotPresent

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClass: default
    size: 4Gi

  volumeMounts:
    mountPath: /var/lib/mysql

  env:
    - name: MARIADB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: mysql-password

  service:
    port: 3306
    type: ClusterIP

  resources: {}
    # requests:
    #   memory: 128Mi
    #   cpu: 0.1
    # limits:
    #   memory: 256Mi
    #   cpu: 0.5